# Form implementation generated from reading ui file 'note_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NoteForm(object):
    def setupUi(self, noteForm):
        noteForm.setObjectName("noteForm")
        noteForm.resize(500, 600)

        self.verticalLayout = QtWidgets.QVBoxLayout(noteForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=noteForm)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        self.titleLineEdit = QtWidgets.QLineEdit(parent=noteForm)
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.horizontalLayout.addWidget(self.titleLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(parent=noteForm)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.buttonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.buttonsHorizontalLayout.setObjectName("buttonsHorizontalLayout")
        self.savePushButton = QtWidgets.QPushButton(parent=noteForm)
        self.savePushButton.setObjectName("savePushButton")
        self.buttonsHorizontalLayout.addWidget(self.savePushButton)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsHorizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.buttonsHorizontalLayout)

        self.retranslateUi(noteForm)
        QtCore.QMetaObject.connectSlotsByName(noteForm)

    def retranslateUi(self, noteForm):
        _translate = QtCore.QCoreApplication.translate
        noteForm.setWindowTitle(_translate("noteForm", "Note"))
        self.titleLabel.setText(_translate("noteForm", "Title:"))
        self.savePushButton.setText(_translate("noteForm", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    noteForm = QtWidgets.QWidget()
    ui = Ui_NoteForm()
    ui.setupUi(noteForm)
    noteForm.show()
    sys.exit(app.exec())
